# Generated by Django 4.1 on 2022-09-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_infocomtask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
