# Generated by Django 4.1 on 2022-09-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_infocomtask', '0002_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
